using:
  engine: openai
  model: gpt-4o

jobs:
  update-code:
    type: agent
    steps:
      - role: system
        content: |
          You are a software developer tasked with updating the code for a command line typescript application.
      - role: user
        content: |
          Extract the all the interfaces from this typescript file related to the `JobConfig` interface and all `Job` subclasses.
          Return only the code and nothing else. Please do not include any preamble or explanation in the response.

          ```typescript
          ${input}
          ```
        replace:
          - pattern: ${input}
            source: file
            name: ./src/utils/job.ts
        response:
          - action: save-to-variables
            output: functions
      - role: user
        content: |
          Generate code that checks the type of all interfaces in the code below. The function names should be of the form `isJobConfig` and use if else statements instead of chaining ternary operators.

          Include logging before each failure check in the form of `Display.debug.log("<error message>")`.

          Cast into the correct type in the functions for types that inherits from others so that the typescript checker does not throw an error

          Export all functions. Do not import any external functions.

          Return only the code and nothing else, not even the markdown syntax. Please do not include any preamble or explanation in the response.

          ${input}
        replace:
          - pattern: ${input}
            name: functions
        response:
          - action: write-to-disk
            output: ./output/job-types.ts
