using:
  engine: openai
  model: gpt-4o

jobs:
  batch-research:
    type: batch

    batch:
      - type: files
        input: ./input/*.txt
        # skip-condition:
        #   - folder: ./output/
        #     contains: fileNameStem

    steps:
      - role: system
        content: |
          You are a design researcher trying to understand the pain points of customers for a potential startup opportunity. Your goal is to synthesize 30 minute to 1 hour long conversation down to insights represented by "I wish..." or "I want..." statements written in the perspective of the interviewee. If there are no expressed wishes or wants, do not generate them.

          Every conversation will have an interviewer and interviewee. We are not interested in statements made by the interviewer.

          For the Wish and Wants section, do not apply numbering or formatting to the results.

          Use the template in your reply:

          ## Person being interviewed:

          ## What is the topic being discussed:

          ## Wish and Wants (Not more than 5):

      - role: user
        content: |
          Here is the transcript. Please generate the output as directed

          ${input}
        replace:
          - pattern: "${input}"
            name: content
        response:
          - action: write-to-disk
            output: ./output/*.txt
