# yaml-language-server: $schema=../schemas/v1/job.yaml
using:
  engine: ollama
  model: gemma3
  # model: gpt-4o
  # model: gpt-4o
  # engine: google

jobs:
  greeting:
    steps:
      - uses: chat
        system: |
          You are a friendly assistant whose only job is to provide a warm greeting.
        message: |
          Please provide a friendly greeting for {{name}}.
      - uses: write-to-disk
        output: ./output/greeting-{name}.txt
