using:
  engine: anthropic

jobs:
  topicGenerator:
    steps:
      - uses: chat
        message: |
          Generate an interesting topic for a blog post about: {{theme}}

          The topic should be:
          - Engaging and clickable
          - Specific and actionable
          - Relevant to the theme

          Return just the topic title.
        output:
          topicGenerator: string

  outlineCreator:
    dependsOn: topicGenerator
    steps:
      - uses: chat
        message: |
          Create a detailed outline for this blog post topic: {{topicGenerator}}

          Include:
          - Introduction hook
          - 3-5 main sections with subsections
          - Conclusion with call-to-action

          Format as a structured outline.
        output:
          outlineCreator: string

  keywordResearcher:
    dependsOn: topicGenerator
    steps:
      - uses: chat
        message: |
          Research relevant keywords and SEO terms for this topic: {{topicGenerator}}

          Provide:
          - 5 primary keywords
          - 10 related long-tail keywords
          - Content optimization suggestions
        output:
          keywordResearcher: string

  contentWriter:
    dependsOn: [outlineCreator, keywordResearcher]
    steps:
      - uses: chat
        message: |
          Write a complete blog post using:

          Topic: {{topicGenerator}}
          Outline: {{outlineCreator}}
          Keywords: {{keywordResearcher}}

          Requirements:
          - Engaging introduction
          - Well-structured content following the outline
          - Natural keyword integration
          - Strong conclusion
          - Approximately {{wordCount}} words

          Format as clean markdown.
        output:
          contentWriter: string

  fileSaver:
    dependsOn: contentWriter
    steps:
      - uses: write-to-disk
        output: ./output/blog-post.md
        keys:
          - contentWriter
