# yaml-language-server: $schema=../schemas/v1/job.yaml
using:
  engine: googleai

jobs:
  pdf:
    steps:
      - uses: chat
        message: |
          Get me the first paragraph of the document.
        documents:
          - file: examples/data/designing-a-new-foundation.pdf
