# yaml-language-server: $schema=../schemas/v1/job.yaml
using:
  engine: ollama
  model: gemma3

jobs:
  image:
    steps:
      - uses: chat
        message: |
          What are the data that is shown in the image.
        images:
          - file: examples/data/economist-brainy-imports.png
