using:
  # engine: openai
  engine: google

jobs:
  musician-research:
    type: serial
    tools:
      - brave
    steps:
      - uses: chat
        system: |
          You are a researcher trying to find out about this musician or band.
        message: |
          You are trying to find out about this musical act: {{name}} .
          Use the tools to collate a short biography, their recent discograph, and their upcoming tour dates and locations based on results on the internet.
      - uses: write-to-disk
        output: ./output/{name}.txt
