using:
  engine: anthropic
  model: claude-3-5-sonnet-20240620

jobs:
  update-readme:
    type: agent
    steps:
      - role: system
        content: |
          You are a technical writer tasked with updating the README.md file for an open source project hosted on GitHub.
      - role: user
        content: |
          Write the readme file in the GitHub format for axle. axle stands for AI eXecution and Logic Engine. Write the readme assuming that the user is You.

          axle is a command line tool for running workflows against LLM APIs. Users can create complex multi-step workflows and interact with the file system. As such, the tool is useful for complex interactions and automating repetitive tasks.

          Include the following sections:
            - Introduction
            - Installation
            - Usage
            - Configuration format
            - Job file format

          The source code for the repository is here: ${input}
        replace:
          - pattern: ${input}
            source: many-files
            name:
              - ./src/**/*.ts
              - ./examples/*.yml
              - ./package.json
        response:
          - action: write-to-disk
            output: ./output/readme.md
